---
# Installs Zookeeper

- name: Fetch zookeeper
  get_url: url=http://mirror.reverse.net/pub/apache/zookeeper/stable/zookeeper-{{ zookeeper_version }}.tar.gz
           dest=/var/tmp/zookeeper-{{ zookeeper_version }}.tar.gz

- name: Extract zookeeper
  command: tar xzf zookeeper-{{ zookeeper_version }}.tar.gz
           chdir=/var/tmp
           creates=/var/tmp/zookeeper-{{ zookeeper_version }}

- name: Install packages required for building a zookeeper package
  apt: pkg={{ item }} state=present
  with_items:
    - ant
    - libtool
    - libcppunit-dev
    - autoconf
    - python-dev
    - build-essential

- name: Remove sun-java6-jre dependency
  lineinfile: dest="/var/tmp/zookeeper-{{ zookeeper_version }}/src/packages/deb/zookeeper.control/control"
              regexp="^Depends"
              state=absent

- name: Create zookeeper debian package
  command: ant deb
           chdir=/var/tmp/zookeeper-{{ zookeeper_version }}
           creates=/var/tmp/zookeeper-{{ zookeeper_version }}/build/zookeeper_{{ zookeeper_version }}-1_amd64.deb

- name: Install zookeeper
  apt: deb="/var/tmp/zookeeper-{{ zookeeper_version }}/build/zookeeper_{{ zookeeper_version }}-1_amd64.deb"
       state=installed

- name: Fix zookeeper startup script to be ran by bash
  lineinfile: dest=/etc/init.d/zookeeper
              regexp="^#!"
              line="#! /usr/bin/env bash"
              state=present
  notify: restart zookeeper

- name: Replace JRE6 with JRE8
  lineinfile: dest=/etc/zookeeper/zookeeper-env.sh
              regexp="^export JAVA_HOME"
              line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre"
              state=present
  notify: restart zookeeper

- name: Set the zookeeper node ID
  copy: content='1' dest=/var/lib/zookeeper/data/myid
  notify: restart zookeeper

- name: Ensure Zookeeper is running and enabled
  service: name=zookeeper state=started enabled=yes
