---
# Installs Redis

- name: Add Redis repository
  apt_repository: repo='ppa:chris-lea/redis-server' state=present

- name: Install Redis
  apt: pkg=redis-server={{ redis_version }} state=present update_cache=yes

- name: Listen on all interfaces
  lineinfile: dest=/etc/redis/redis.conf regexp="^bind" line="bind 0.0.0.0" state=present
  notify: restart redis

- name: Enable keepalives
  lineinfile: dest=/etc/redis/redis.conf regexp="^tcp-keepalive" line="tcp-keepalive 60" state=present
  notify: restart redis

- name: Ensure redis is running and enabled
  service: name=redis-server state=started enabled=yes
