---
# Installs InfluxDB

- name: Add the influxdb apt key
  apt_key: url=https://repos.influxdata.com/influxdb.key id=2582E0C5 state=present

- name: Add the influxdb apt repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable'
                  state=present

- name: Install influxdb
  apt: name=influxdb={{ influxdb_version }}
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Install the influxdb configuration file
  copy: src=etc_influxdb_influxdb.conf
        dest=/etc/influxdb/influxdb.conf
        owner=root
        group=root
        mode=0644
  notify: restart influxdb

- name: Ensure influxdb is running and enabled
  service: name=influxdb state=started enabled=yes
