---
# Installs MongoDB

- name: Ensure repository key for MongoDB is in place
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10 state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse'
                  state=present

- name: Copy mongod.conf into place
  copy: src=etc_mongod.conf
        dest=/etc/mongod.conf
        owner=root
        group=root
        mode=644
  notify: restart mongodb

- name: Install MongoDB
  apt: pkg=mongodb-org={{ mongodb_version }} state=present update_cache=yes

- name: Ensure MongoDB is running and enabled
  service: name=mongod state=started enabled=yes
