---
# Installs MongoDB

- name: Ensure repository key for MongoDB is in place
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: Install MongoDB
  apt: pkg=mongodb-10gen state=present update_cache=yes

- name: Ensure MongoDB is running and enabled
  service: name=mongodb state=started enabled=yes
