---

- hosts: all
  user: ubuntu
  sudo: True
  gather_facts: True
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'testing' if testing is defined else 'user' }}.yml

  roles:
    - common
    - riak
    - rabbitmq
    - elasticsearch
    - redis
    - mongodb
    - postgresql
    - mysql
    - zookeeper
    - docker
    - kafka
    - mesos
    - riemann
    - influxdb
    - cassandra
    - rethinkdb
    #- kong
