---
# Installs Kafka

- name: Create the kafka group
  group: name=kafka system=yes state=present

- name: Create the kafka user
  user: name=kafka
        group=kafka
        system=yes
        createhome=no
        home=/usr/local/kafka
        shell=/bin/false
        state=present

- name: Fetch kafka
  get_url: url=http://mirrors.ibiblio.org/apache/kafka/{{ kafka_version }}/kafka_2.10-{{ kafka_version }}.tgz
           dest=/usr/local/kafka_2.10-{{ kafka_version }}.tgz

- name: Extract kafka
  command: tar xzf kafka_2.10-{{ kafka_version }}.tgz
           chdir=/usr/local
           creates=/usr/local/kafka_2.10-{{ kafka_version }}

- name: Symlink kafka
  file: src=/usr/local/kafka_2.10-{{ kafka_version }}
        dest=/usr/local/kafka
        owner=kafka
        group=kafka
        force=yes
        state=link

- name: Fix directory permissions
  file: path=/usr/local/kafka_2.10-{{ kafka_version }}
        state=directory
        owner=kafka
        group=kafka
        recurse=yes

- name: Create logs directory
  file: path=/usr/local/kafka/logs
        state=directory
        owner=kafka
        group=kafka

- name: Enable Kafka
  lineinfile: dest=/etc/default/kafka
              line="KAFKA_ENABLED=yes"
              state=present
              create=yes
              owner=root
              group=root
              mode=644

- name: Advertise on localhost
  lineinfile: dest=/usr/local/kafka/config/server.properties
              line="advertised.host.name=localhost"
              regexp="^advertised.host.name"
              insertafter="^#advertised.host.name"
              state=present
  notify: restart kafka

- name: Copy upstart script into place
  copy: src=etc_init_kafka.conf
        dest=/etc/init/kafka.conf
        owner=root
        group=root
        mode=640
  notify: restart kafka

- name: Ensure Kafka is running and enabled
  service: name=kafka state=started enabled=yes