---
# Installs Kafka

- name: Create the kafka group
  group: name=kafka system=yes state=present

- name: Create the kafka user
  user: name=kafka
        group=kafka
        system=yes
        createhome=no
        home=/usr/local/kafka
        shell=/bin/false
        state=present

- name: Fetch kafka
  get_url: url=http://mirrors.ibiblio.org/apache/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz
           dest=/usr/local/kafka_2.11-{{ kafka_version }}.tgz

- name: Extract kafka
  unarchive: src=/usr/local/kafka_2.11-{{ kafka_version }}.tgz
             dest=/usr/local
             creates=/usr/local/kafka_2.11-{{ kafka_version }}
             copy=no

- name: Symlink kafka
  file: src=/usr/local/kafka_2.11-{{ kafka_version }}
        dest=/usr/local/kafka
        owner=kafka
        group=kafka
        force=yes
        state=link

- name: Fix directory permissions
  file: path=/usr/local/kafka_2.11-{{ kafka_version }}
        state=directory
        owner=kafka
        group=kafka
        recurse=yes

- name: Create logs directory
  file: path=/usr/local/kafka/logs
        state=directory
        owner=kafka
        group=kafka

- name: Copy kafka server.properties into place
  copy: src=usr_local_kafka_config_server.properties
        dest=/usr/local/kafka/config/server.properties
        owner=kafka
        group=kafka
        mode=0644
  notify: restart kafka

- name: Copy upstart script into place
  copy: src=etc_init_kafka.conf
        dest=/etc/init/kafka.conf
        owner=root
        group=root
        mode=0644
  notify: restart kafka

- name: Ensure Kafka is running and enabled
  service: name=kafka state=started enabled=yes
