---
# Installs RabbitMQ

- name: Ensure repository key for RabbitMQ is in place
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Add RabbitMQ repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Install RabbitMQ
  apt: pkg=rabbitmq-server state=present update_cache=yes

- name: Increase maximum open file handle limit
  lineinfile: dest=/etc/default/rabbitmq-server regexp=^ulimit line="ulimit -n 65536" state=present
  notify: restart rabbitmq

- name: Register currently enabled plugins
  shell: /usr/sbin/rabbitmq-plugins list -E -m
  register: plugins

- name: Enable RabbitMQ management plugin
  command: /usr/sbin/rabbitmq-plugins enable rabbitmq_management
  when: plugins.stdout.find('rabbitmq_management') == -1
  notify: restart rabbitmq
