---
# Installs RabbitMQ

- name: Ensure repository key for RabbitMQ is in place
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
           id=056E8E56
           state=present

- name: Add RabbitMQ repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main'
                  state=present

- name: Install RabbitMQ
  apt: pkg=rabbitmq-server={{ rabbitmq_version }}
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Increase maximum open file handle limit
  lineinfile: dest=/etc/default/rabbitmq-server
              regexp=^ulimit
              line="ulimit -n 65536"
              state=present
  notify: restart rabbitmq

- name: Enable RabbitMQ management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq

- name: Allow the guest user to connect remotely
  copy: src=etc_rabbitmq_rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq

- name: Ensure RabbitMQ is running and enabled
  service: name=rabbitmq-server state=started enabled=yes
