---
# Installs Riak

- name: Ensure repository key for packagecloud.io is in place
  apt_key: url=https://packagecloud.io/gpg.key id=D59097AB state=present

- name: Add packagecloud.io repository
  apt_repository: repo="deb https://packagecloud.io/basho/riak/ubuntu/ trusty main"
                  state=present

- name: Install Riak
  apt: pkg=riak={{ riak_version }}
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Copy riak.conf into place
  copy: src=etc_riak_riak.conf
        dest=/etc/riak/riak.conf
        owner=riak
        group=riak
  notify: restart riak

- name: Create /etc/default/riak
  copy: content="ulimit -n 65536"
        dest=/etc/default/riak
        owner=root
        group=root
        mode=0644
  notify: restart riak

- name: Update open file limits for Riak
  lineinfile: dest=/etc/security/limits.conf
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: "^riak soft", line: "riak soft nofile 65536" }
    - { regexp: "^riak hard", line: "riak hard nofile 65536" }
  notify: restart riak

- name: Optimize Riak sysctl settings
  sysctl: name="{{ item.name }}"
          value={{ item.value }}
          state=present
          sysctl_set=yes
          reload=yes
  with_items:
    - { name: "fs.file-max",                  value: 65536 }
    - { name: "vm.swappiness",                value: 0 }
    - { name: "vm.dirty_bytes",               value: 209715200 }
    - { name: "vm.dirty_background_bytes",    value: 104857600 }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 40000 }
    - { name: "net.core.somaxconn",           value: 40000 }
    - { name: "net.ipv4.tcp_sack",            value: 1 }
    - { name: "net.ipv4.tcp_window_scaling",  value: 1 }
    - { name: "net.ipv4.tcp_fin_timeout",     value: 15 }
    - { name: "net.ipv4.tcp_keepalive_intvl", value: 30 }
    - { name: "net.ipv4.tcp_tw_reuse",        value: 1 }
    - { name: "net.ipv4.tcp_moderate_rcvbuf", value: 1 }
    - { name: "net.core.wmem_default",        value: 134217728 }
    - { name: "net.core.rmem_default",        value: 134217728 }
    - { name: "net.core.wmem_max",            value: 134217728 }
    - { name: "net.core.rmem_max",            value: 134217728 }
    - { name: "net.core.netdev_max_backlog",  value: 300000 }
  notify: restart riak

# Was not able to set these using the sysctl module
- name: Add additional Riak sysctl settings
  lineinfile: dest=/etc/sysctl.conf
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
              state=present
  with_items:
    - { regexp: "^net.ipv4.tcp_mem",  line: "net.ipv4.tcp_mem = 134217728 134217728 134217728" }
    - { regexp: "^net.ipv4.tcp_rmem", line: "net.ipv4.tcp_rmem = 4096 277750 134217728" }
    - { regexp: "^net.ipv4.tcp_wmem", line: "net.ipv4.tcp_wmem = 4096 277750 134217728" }
  notify: restart riak

- name: Register current scheduler
  shell: cat /sys/block/{{ block_device }}/queue/scheduler
  register: scheduler

- name: Change default scheduler on {{ block_device }}
  shell: echo deadline > /sys/block/{{ block_device }}/queue/scheduler
  when: scheduler.stdout.find('[deadline]') == -1

- name: Register current scheduler depth
  shell: cat /sys/block/{{ block_device }}/queue/nr_requests
  register: nr_requests

- name: Increase scheduler depth
  shell: echo 1024 > /sys/block/{{ block_device }}/queue/nr_requests
  when: nr_requests.stdout.find('1024') == -1

- name: Ensure Riak is running and enabled
  service: name=riak state=started enabled=yes
