---
# Installs Marathon

- name: Install Marathon
  apt: pkg=marathon={{ marathon_version }}
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Ensure Marathon is running and enabled
  service: name=marathon state=started enabled=yes
