---
# Installs Mesos

- name: Ensure repository key for Mesos is in place
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesos repository
  apt_repository: repo='deb http://repos.mesosphere.io/ubuntu/ trusty main'
                  state=present

- name: Install Mesos
  apt: pkg=mesos={{ mesos_version }}
       state=present
       update_cache=yes
       cache_valid_time=3600

- name: Configure the Mesos Slave containerizers value
  copy: content='docker,mesos'
        dest=/etc/mesos-slave/containerizers
  notify: restart mesos slave

- name: Configure the Mesos Slave executor_registration_timeout value
  copy: content='5mins'
        dest=/etc/mesos-slave/executor_registration_timeout
  notify: restart mesos slave

- name: Ensure Mesos Master is running and enabled
  service: name=mesos-master state=started enabled=yes

- name: Ensure Mesos Slave is running and enabled
  service: name=mesos-slave state=started enabled=yes
