---
# Defines tasks applicable for Oracle Java

- name: Ensure WebUpd8 repository is installed
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept oracle license
  debconf: name='oracle-java8-installer'
           question='shared/accepted-oracle-license-v1-1'
           value='true'
           vtype='select'

- name: Install Oracle JRE
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default