---
# Defines tasks applicable across all machines in the infrastructure.

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=present
  with_items:
    - sudo
    - tcsh
    - python-software-properties

- name: Install unattended upgrades (Debian/Ubuntu only)
  apt: pkg=unattended-upgrades state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: ntp.yml tags=ntp
- include: users.yml tags=users
- include: java.yml tags=java
