---
# Installs Docker

- name: Add Docker APT key
  apt_key: url=https://get.docker.io/gpg id=A88D21E9 state=present

- name: Add Docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: Install Docker
  apt: pkg=lxc-docker={{ docker_version }} state=present update_cache=yes

- name: Add users to docker group
  user: name={{ item }} groups=docker append=yes
  with_items:
    - vagrant
    - "{{ main_user_name }}"

- name: Ensure docker is running and enabled
  service: name=docker state=started enabled=yes
