---

- name: restart postgresql
  service: name=postgresql state=restarted

- name: set postgres password
  command: sudo -u postgres psql -d postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"