---
# Installs Exhibitor

- name: Fetch exhibitor pom file
  get_url: url=https://raw.githubusercontent.com/Netflix/exhibitor/{{ exhibitor_version }}/exhibitor-standalone/src/main/resources/buildscripts/standalone/maven/pom.xml
           dest=/root/pom.xml

- name: Install maven for building a exhibitor package
  apt: pkg=maven state=present

- name: Build exhibitor
  command: mvn assembly:single
           chdir=/root
           creates=/root/target/exhibitor-1.0-jar-with-dependencies.jar

- name: Create exhibitor directory
  file: path=/usr/local/exhibitor
        owner=root
        group=root
        state=directory

- name: Copy exhibitor into directory
  command: cp /root/target/exhibitor-1.0-jar-with-dependencies.jar /usr/local/exhibitor/
           creates=/usr/local/exhibitor/exhibitor-1.0-jar-with-dependencies.jar

- name: Copy exhibitor.properties into directory
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: usr_local_exhibitor_exhibitor.properties, dest: /usr/local/exhibitor/exhibitor.properties }
    - { src: usr_local_exhibitor_log4j.xml, dest: /usr/local/exhibitor/log4j.xml }
  notify: restart exhibitor

- name: Install exhibitor upstart script
  copy: src=etc_init_exhibitor.conf
        dest=/etc/init/exhibitor.conf
        owner=root
        group=root
        mode=644
  notify: restart exhibitor

- name: Ensure Exhibitor is running and enabled
  service: name=exhibitor state=started enabled=yes
